### ISSUE TITLE
Dark mode transition bug

### ISSUE THREAD

**Issue by naveen-bharathi** [TablePlus/TablePlus-iOS#1]
TablePlus iOS v1.121 (Build 126)

When changing the appearance of the iOS device from light to dark or dark to light, the connection screen shows ugly UI

Steps to reproduce:

• Open the TablePlus App in the iOS device
• Go to the connections page
• Toggle the device appearance to the opposite of current appearance.
![56DFF45B-BB08-4901-B3E7-B93781447AC1](https://user-images.githubusercontent.com/32498535/70863564-887dd400-1f6f-11ea-9a2d-5ad131c34dd7.png)
![F1D7C7F6-520B-4A9E-A388-FFC494AEA02B](https://user-images.githubusercontent.com/32498535/70863567-887dd400-1f6f-11ea-85c1-62e8cb3120af.png)
![6E7A4DD3-006A-4C21-8832-7B03DEB9AC8A](https://user-images.githubusercontent.com/32498535/70863570-89166a80-1f6f-11ea-8d95-191b30184cba.png)
![BFD13B70-604A-4F97-8A43-0AEF297749F0](https://user-images.githubusercontent.com/32498535/70863572-89af0100-1f6f-11ea-8788-0809853f2099.png)

**Comment by huyphams** [comment]
It's fixed on build 130 AppStore now. Thanks!
