### ISSUE TITLE
TAB does not move between columns

### ISSUE THREAD

**Issue by giulianov** [TablePlus/TablePlus-iOS#10]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): irrelevant

2. Which TablePlus version number are you using: build 292

3. The steps to reproduce this issue: open a table, enter in a field either in the table view or in the record pane, type a value (not necessary), press TAB to move to the next column. The TAB is entered as a tab!

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi @giulianov please update to our latest release and see how it goes.
Thanks

**Comment by huyphams** [comment]
Hi, it would be great if you can update it, we apprecate your feedback however bad rating could result in lower ranking and the app reputation and lower income😞
![7AD31C48-30E2-4F6C-B863-1E60E07E676C](https://user-images.githubusercontent.com/3654622/130650906-d33c16dd-9e7c-499d-9316-5617e8523eb0.jpeg)
