### ISSUE TITLE
Datetime values saved as strings

### ISSUE THREAD

**Issue by giulianov** [TablePlus/TablePlus-iOS#11]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 

2. Which TablePlus version number are you using: build 292
 
3. The steps to reproduce this issue: in a new or old record, select a datetime column and enter the function now() as a value. When saving it is sent as a string. You can also see that that is the case by pressing the eye icon, this shows the SQL command where the function is surrounded by single quotes. The datetime is then interpreted as the 0000-00- etc value. It does not happen for numeric columns. 

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
It should be fixed in our latest release.
