### ISSUE TITLE
TablePlus for IOS, no way to import private SSH key. "Please enter SSH private key password"

### ISSUE THREAD

**Issue by andyseavers** [TablePlus/TablePlus-iOS#11]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): PostegreSQL

2. Which TablePlus version number are you using: Current IOS Build 1.11.1

3. The steps to reproduce this issue: Connect a database with SSH Key.

**Comment by andyseavers** [comment]
No password exists. Must upload SSH key to access.

**Comment by huyphams** [comment]
I don't quite understand the issue @andyseavers are you trying to connect to the server using server password?

**Comment by huyphams** [comment]
Please turn off this toggle button in order to use the server password @andyseavers 
![ssh](https://user-images.githubusercontent.com/3654622/66445681-f5c83280-ea1d-11e9-819a-1a16610e2698.png)

**Comment by huyphams** [comment]
Currently, TablePlus does not support import private key, you have to copy the content of your private key and paste it into the box below the toggle button above.

**Comment by andyseavers** [comment]
Saw this got added in the last IOS release. Amazing! Thanks so much.
