### ISSUE TITLE
SELECT IN filter with string values throws error

### ISSUE THREAD

**Issue by echo-blue** [TablePlus/TablePlus-iOS#15]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0): MySQL 5.7.12

2. Which TablePlus version number are you using: v4.8.1 (Build 326) on iOS 15.1

3. The steps to reproduce this issue:
With a DB table open, using the `IN` filter with the following values throws an error (see screenshot): `"marcus","michael"`
I have tried different tables, different columns, double quotes and single quotes.
Writing the SQL statement out in the editor works:
`SELECT * FROM users WHERE FirstName IN ("marcus","michael");`

![IMG_7DABB43C0000-1](https://user-images.githubusercontent.com/48693401/145357704-e9723863-676f-4c0c-b53e-83f937a965fa.jpeg)

**Comment by huyphams** [comment]
It should be fixed on the newest release.
issue: we disabled the iOS text field smart quote, which is replacing the double quote to an invalid SQL character.
