### ISSUE TITLE
mysql commit do not work

### ISSUE THREAD

**Issue by jakiestar** [TablePlus/TablePlus-iOS#25]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):mysql 8

2. Which TablePlus version number are you using:5.2.3 build 406

3. The steps to reproduce this issue:
sometimes commit do not work
i can not save data
Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
Hi, we're submitting an update, please wait for a while.

**Comment by jakiestar** [comment]
helloi update to the new version 5.2.5 but the bug did not fixedcommit is not work2023年1月27日，13:15，Henry Pham ***@***.***> ：﻿
Hi, we're submitting an update, please wait for a while.

**Comment by sonswift** [comment]
> helloi update to the new version 5.2.5 but the bug did not fixedcommit is not work2023年1月27日，13:15，Henry Pham ***@***.***> ：

Hi @jakiestar, could you please give me steps to reproduce your issue. 
I tested on MySQL 8.0.27, edited rows in `Table` and in `SQL Query` results had been committed successfully. 

Thanks,
Sonswift.

**Comment by jakiestar** [comment]
helloplease see video2023年1月28日，14:50，Son Thai ***@***.***> 写道：﻿

helloi update to the new version 5.2.5 but the bug did not fixedcommit is not work2023年1月27日，13:15，Henry Pham @.***> ：

Hi @jakiestar, could you please give me steps to reproduce your issue.
I tested on MySQL 8.0.27, edited rows in Table and in SQL Query results had been committed successfully.
Thanks,
Sonswift.

**Comment by sonswift** [comment]
hi @jakiestar , I could not see any videos in this thread? Could you please attach the video in the comment, not in the replied email?

**Comment by jakiestar** [comment]
ok please see it here
i will delete the video tomorrow
you can download it

**Comment by jakiestar** [comment]
ok please see it here
i will delete the video tomorrow
you can download it

**Comment by sonswift** [comment]
sr, but nothing's here 
<img width="925" alt="CleanShot 2023-01-28 at 14 14 49@2x" src="https://user-images.githubusercontent.com/4739616/215252638-2f6c0930-22e0-4bbe-9364-20dfd8b17dd2.png">

**Comment by jakiestar** [comment]
https://www.icloud.com/iclouddrive/0eacmBcnJxB5dSYy95N3OQqOA#RPReplay_Final1674885908
you can see it here

**Comment by jakiestar** [comment]
> sr, but nothing's here
> <img alt="CleanShot 2023-01-28 at 14 14 49@2x" width="925" src="https://user-images.githubusercontent.com/4739616/215252638-2f6c0930-22e0-4bbe-9364-20dfd8b17dd2.png">

did you see that？
if you can not see it
i will upload to YouTube

**Comment by sonswift** [comment]
hi @jakiestar, I saw the video and downloaded it. I'm trying to reproduce and find out the problem. But not finish yet. I will inform you if any updates. Thanks for you support.

**Comment by huyphams** [comment]
Hi @jakiestar could you click the eye button and show us the generated queries please?

**Comment by jakiestar** [comment]
UPDATE `yukihara`.`订单记录` SET `备注` = '1' WHERE `id` = 184379;

**Comment by jakiestar** [comment]
the bug don't appear every time.
With a probability of about 20%, it will commit to success.

**Comment by huyphams** [comment]
I can reproduce the issue now. thanks!

**Comment by huyphams** [comment]
the bug happen after the app came back from the background (after the database is disconnected). The app is in-review now, please wait for a while.

**Comment by jakiestar** [comment]
i do not think so.
i also first filter the row that i want update.

the "select" is ok, it means connect is not closed

**Comment by huyphams** [comment]
Yep, the select is fine but the items which are opened are not, they will not be updated. You can reproduce the issue with the following steps:
1. Open a connection.
2. Open a table.
3. Hold the finger on the status bar, and select disconnect.
4. Tap again on the status bar to connect.
5. Edit the table content and commit, it will not save.

**Comment by jakiestar** [comment]
yes！
you are right

**Comment by huyphams** [comment]
It should be fixed, please update the app!.
