### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by MiniCodeMonkey** [TablePlus/TablePlus-iOS#3]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
n/a

2. Which TablePlus version number are you using:
TablePlus on iPad Pro
Version 3.42 (Build 190)

3. The steps to reproduce this issue:

This bug appeared shortly after I created the connections (about a year ago when the app was first released). I sat on it, hoping that an app update would fix it. But it is still an issue.

![7EFE8578-E651-4885-A2C3-B50ECCF4AB5B](https://user-images.githubusercontent.com/220535/80165227-03ec3380-85a9-11ea-8478-b96a96494e67.jpeg)

Noted: If the bug is related to data, please attach an example SQL data.

**Comment by huyphams** [comment]
I don't see any issue with it @MiniCodeMonkey could you point me out? Thank you!

**Comment by MiniCodeMonkey** [comment]
All but 2 of the connections are missing their name which makes it really difficult to figure out what is what.  When I click "Edit" I can clearly see that they are all named. If you look closely there's also some rendering artifact (the black dots and the light-grey stretched button)

**Comment by MiniCodeMonkey** [comment]
Thanks for the super quick response by the way!

**Comment by sonswift** [comment]
Hi @MiniCodeMonkey, can you send me some of the names of name-missing connections?
