### ISSUE TITLE
Tableplus with Private Key

### ISSUE THREAD

**Issue by chrisgo** [TablePlus/TablePlus-iOS#33]
### Please answer the questions below, it helps us to track the issue.

1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):

MySQL Connection

2. Which TablePlus version number are you using:

6.1.8 (Build 534) on iPad Air (5th gen) with iOS 18.0 (22A3354)

3. The steps to reproduce this issue:

* Create a new connection
* Select MySQL Connection
* Database Host: 127.0.0.1 (port is default)
* Database User: developer 
* Database Password: ******
* Over SSH (turn on)
* Server Address: prd-mdb8.domain.com (Server port: 22)
* Server User: developer
* Server Password: (blank)
* Use private key (turn on) then "Import Key" and locate **private key** (~/Users/chrisgo/.ssh/id_rsa) of a pub key that is on the server
* Click on Test

![IMG_0013](https://github.com/user-attachments/assets/2ac76b69-356e-4c23-b1a5-e94f53a7da23)

Tableplus cannot connect and a popup shows up "Error Invalid host private key"

Expectation is that it will prompt me for the MFA code "popup" (6 digit OTP)

I am using the MacOS version of Tableplus with the exact same settings and exact same id_rsa file as above and it connects and prompts for the OTP 

<img width="500" alt="Screenshot 2024-09-28 at 22 08 35" src="https://github.com/user-attachments/assets/d188c508-b43f-4372-9a51-98721d580169">

<img width="1181" alt="Screenshot 2024-09-28 at 22 13 23" src="https://github.com/user-attachments/assets/9224e136-f1dd-4e2b-a6c4-a09ec79d047d">

On the MacOS app, if you fail to provide the 6 digit OTP, it will show the same "Error Invalid host private key" so it seems like the iOS app is not even getting there but cannot really tell.  

* Is there a way for me to understand how this fails or some type of log somewhere?
* Does the red background (on the UI) of the private key indicate anything when you hit test.  It is white before you click on "Test" and it becomes red afterward

**Comment by huyphams** [comment]
Hi,
We just release the build 6.1.9 build 536 which should address this issue.

**Comment by chrisgo** [comment]
Confirmed working on 6.1.9 - thank you very much!!!!
