### ISSUE TITLE
Setapp for iOS - Hook it up!

### ISSUE THREAD

**Issue by skwaugh** [TablePlus/TablePlus-iOS#6]
What's the hold up!  

TablePlus is, by far, my favorite app on Setapp and accounts for at least 90% of my Setapp usage.
I'm not alone in that either - that goes for my team, too.  (sidebar - I do hope that Macpaw's payment distribution is akin to Spotify's  pay-per-stream.  Ya'll deserve it)

I signed up my team for Setapp iOS on all of our iPads and iPhones because I knew that Tableplus was already alive and well on mobile...of course it would be included in the inaugural release of Setapp for iOS, right?  

Nope.  Still waiting, months later.  I understand that you may make more dough charging $40 per install on iOS, but you're never going to get existing Setapp users to shell out that cash on top of Setapp.

Tableplus is worth the Setapp fee, alone.  If you have to lobby MacPaw to raise their prices a buck or two - no problem.  Just please make it happen for your loyal customers.

Thank you for building an awesome product.

**Comment by huyphams** [comment]
Hi, we don't want to take any risk with the Setapp licensing (also it does not contribute much to our revenue). We provide the iOS version for free for our PC license owner by going to TablePlus iOS settings > Unlock with a desktop key.

**Comment by skwaugh** [comment]
well if its not so great, then get off Setapp so that they can replace you with a comprehensive Desktop+Mobile solution?

**Comment by huyphams** [comment]
"We don't want to take any risk with the Setapp licensing" I mean, it violates the Apple guideline that could result in losing the TablePlus Inc account.
