### ISSUE TITLE
Bug: Cannot use SSH connection without providing SSH Private Key Password

### ISSUE THREAD

**Issue by n8udd** [TablePlus/TablePlus-iOS#7]
I've imported connection settings from TablePlus for Mac, and tried adding the connection manually.

I'm using an `id_rsa` key, without a password for connection via SSH.

This works fine on my Mac, but on the iOS app it keeps prompting me for a password. Leaving it blank and pressing either OK or Cancel doesn't work.

**Comment by huyphams** [comment]
Hi, just wanna confirm that did you import the correct private key?

**Comment by n8udd** [comment]
Apologies, it was using the default ssh key, rather than the specific one I should have been using for this connection.
