### ISSUE TITLE
Database name field missing for MySQL 

### ISSUE THREAD

**Issue by davidolrik** [TablePlus/TablePlus-iOS#8]
In the settings dialog for MySQL there is no field for the database name.

This prohibits me from connecting to databases where I only have access to a specific database.

**Comment by huyphams** [comment]
Hi, TablePlus iOS optimizes the connection from and remove all optional fields. You can connect to MySQL without the database.
if you choose a database in the app, TablePlus will remember it for the next time.

**Comment by huyphams** [comment]
It's added in the next update.

**Comment by davidolrik** [comment]
The field is there now, but the database I enter is not selected when connecting.
