### ISSUE TITLE
Support more cmd-x shortcuts.

### ISSUE THREAD

**Issue by tdegrunt** [TablePlus/TablePlus-iOS#9]
1. Which driver are you using and version of it (Ex: PostgreSQL 10.0):
-
2. Which TablePlus version number are you using:
1.7 build 90
3. The steps to reproduce this issue:
Press CMD for a few secs
Noted: If the bug is related to data, please attach an example SQL data.

Some more shortcuts would be very useful. Especially CMD-S for saving and CMD-R for refresh. But CMD-I and CMD-D are very useful too!

**Comment by huyphams** [comment]
TablePlus now supports all those shortcuts, thanks!
